add windows and mac integ tests

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -73,6 +73,22 @@ jobs:
             echo "Expected output not found"
             exit 1
           fi
+  test-integ-test-macos:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v4
+      - run: brew install pre-commit
+      - run: pre-commit install
+      - run: echo >> ./pre_commit_hooks_tests/resources/s3_bucket_logging_enabled.guard
+      - run: git add .
+      - name: Run pre-commit hook
+        run: |
+          output=$(pre-commit run 2>&1 || true)
+          echo $output
+          if ! echo $output | grep -q "exit code: 7"; then
+            echo "Expected output not found"
+            exit 1
+          fi
   validate-integ-test-windows:
     runs-on: windows-latest
     steps:
@@ -89,6 +105,28 @@ jobs:
         run: |
           $output = pre-commit run | Out-String
           if ($output | Select-String -Pattern "exit code: 19") {
+              exit 0
+          } else {
+            Write-Host "Expected output not found"
+            Write-Host $output
+            exit 1
+          }
+  test-integ-test-windows:
+    runs-on: windows-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.10.0'
+      - run: pip install pre-commit
+      - run: pre-commit install
+      - run: '"`n" | Out-File -Append ./pre_commit_hooks_tests/resources/s3_bucket_logging_enabled.guard'
+      - run: git add .
+      - name: Run pre-commit hook
+        shell: powershell
+        run: |
+          $output = pre-commit run | Out-String
+          if ($output | Select-String -Pattern "exit code: 7") {
               exit 0
           } else {
             Write-Host "Expected output not found"
